stages:
  - test
  - npm-build
  - docker-build
  
test:
  stage: test
  script:
    - npm i
    - npm run test
  tags:
    - deploy
  
npm-build:
  stage: npm-build
  artifacts:
    paths:
      - node_modules
  script:
    - npm install --progress=false
  tags:
    - deploy

docker-build:
  stage: docker-build
  script: docker build -t paredros-api .
  tags:
    - deploy